// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "apidoc.App": {
                "properties": {
                    "IAPRange": {
                        "description": "IAPRange is the human-readable in-app-purchase price range; absent when the\napp has no IAP.",
                        "example": "$0.99 - $149.99 per item",
                        "type": "string"
                    },
                    "adSupported": {
                        "description": "AdSupported is true when the listing declares \"Contains ads\".",
                        "example": true,
                        "type": "boolean"
                    },
                    "androidVersion": {
                        "description": "AndroidVersion is the minimum supported Android version; may be empty when\nGoogle reports \"Varies with device\".",
                        "example": "6.0",
                        "type": "string"
                    },
                    "appId": {
                        "description": "AppID is the app package name (the listing's id query parameter).",
                        "example": "com.google.android.apps.maps",
                        "type": "string"
                    },
                    "available": {
                        "description": "Available is true when the listing was reachable and parsed (a 404/region\nblock yields false).",
                        "example": true,
                        "type": "boolean"
                    },
                    "categories": {
                        "description": "Categories is the list of category names the app is filed under.",
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "contentRating": {
                        "description": "ContentRating is the age/content rating label, e.g. \"Everyone\" or\n\"USK: Ages 18+\".",
                        "example": "Everyone",
                        "type": "string"
                    },
                    "contentRatingDescription": {
                        "description": "ContentRatingDescription is the qualifier shown next to ContentRating\n(e.g. \"Gambling with Cash Payouts\"); may be absent.",
                        "example": "Gambling with Cash Payouts",
                        "type": "string"
                    },
                    "currency": {
                        "description": "Currency is the ISO 4217 code for Price/OriginalPrice, e.g. \"USD\", \"EUR\".",
                        "example": "USD",
                        "type": "string"
                    },
                    "description": {
                        "description": "Description is the long description with HTML stripped to plain text;\nnewlines are preserved.",
                        "type": "string"
                    },
                    "descriptionHTML": {
                        "description": "DescriptionHTML is the long description with Google's original inline\nmarkup preserved (mostly \u003cbr\u003e tags and HTML entities).",
                        "type": "string"
                    },
                    "developer": {
                        "description": "Developer is the developer's display name.",
                        "example": "Google LLC",
                        "type": "string"
                    },
                    "developerAddress": {
                        "description": "DeveloperAddress is the developer's postal address; may be empty.",
                        "type": "string"
                    },
                    "developerEmail": {
                        "description": "DeveloperEmail is the developer's contact email; may be empty.",
                        "example": "apps-help@google.com",
                        "format": "email",
                        "type": "string"
                    },
                    "developerId": {
                        "description": "DeveloperID is the developer listing id used by GET /store/apps/developer\n(a numeric id or a quoted name).",
                        "example": "Google LLC",
                        "type": "string"
                    },
                    "developerInternalID": {
                        "description": "DeveloperInternalID is Google's internal developer id; present only for EU\nDSA trader listings.",
                        "type": "string"
                    },
                    "developerLegalAddress": {
                        "description": "DeveloperLegalAddress is the trader's registered address (EU DSA only).",
                        "type": "string"
                    },
                    "developerLegalEmail": {
                        "description": "DeveloperLegalEmail is the trader's legal contact email (EU DSA only).",
                        "format": "email",
                        "type": "string"
                    },
                    "developerLegalName": {
                        "description": "DeveloperLegalName is the trader's registered legal name (EU DSA only).",
                        "type": "string"
                    },
                    "developerLegalPhoneNumber": {
                        "description": "DeveloperLegalPhoneNumber is the trader's contact phone number (EU DSA only).",
                        "type": "string"
                    },
                    "developerWebsite": {
                        "description": "DeveloperWebsite is the developer's website URL; may be empty.",
                        "example": "http://maps.google.com/about/",
                        "format": "uri",
                        "type": "string"
                    },
                    "discountEndDate": {
                        "description": "DiscountEndDate is the discount expiry as a Unix epoch in SECONDS; present\nonly while a discount is active, otherwise 0/absent.",
                        "example": 1735689600,
                        "format": "int64",
                        "minimum": 0,
                        "type": "integer"
                    },
                    "earlyAccessEnabled": {
                        "description": "EarlyAccessEnabled is true when the listing is in early-access state.",
                        "example": false,
                        "type": "boolean"
                    },
                    "free": {
                        "description": "Free is true when Price == 0.",
                        "example": true,
                        "type": "boolean"
                    },
                    "genre": {
                        "description": "Genre is the localized primary category name.",
                        "example": "Travel \u0026 Local",
                        "type": "string"
                    },
                    "genreId": {
                        "description": "GenreID is the stable, uppercased category id (a Play category enum value).\nSee the categories list for the full set; \"GAME_*\" prefixes a game genre.",
                        "example": "TRAVEL_AND_LOCAL",
                        "type": "string"
                    },
                    "headerImage": {
                        "description": "HeaderImage is the feature-graphic banner URL; absent on some listings.",
                        "example": "https://play-lh.googleusercontent.com/UVo1hFs93u3MCQMQo6_KoKrX",
                        "format": "uri",
                        "type": "string"
                    },
                    "histogram": {
                        "description": "Histogram is the rating-count breakdown by star level, indexed\n[0]=1-star .. [4]=5-star. Values are counts, not percentages, and need not\nsum exactly to Ratings.",
                        "example": [
                            5452870,
                            1679546,
                            461292,
                            1082704,
                            9500000
                        ],
                        "items": {
                            "type": "integer"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "icon": {
                        "description": "Icon is the app icon URL.",
                        "example": "https://play-lh.googleusercontent.com/B8pdO_2K5nBsF0g1h6dKwV",
                        "format": "uri",
                        "type": "string"
                    },
                    "installs": {
                        "description": "Installs is the human-formatted install count with grouping separators and\na trailing \"+\", exactly as displayed.",
                        "example": "1,000,000,000+",
                        "type": "string"
                    },
                    "isAvailableInPlayPass": {
                        "description": "IsAvailableInPlayPass is true when the app is included in Google Play Pass.",
                        "example": false,
                        "type": "boolean"
                    },
                    "maxInstalls": {
                        "description": "MaxInstalls is Google's estimated actual install count (an upper bound,\nstrictly \u003e= MinInstalls).",
                        "example": 2263522953,
                        "format": "int64",
                        "minimum": 0,
                        "type": "integer"
                    },
                    "minInstalls": {
                        "description": "MinInstalls is the lower bound of the install bucket as an integer.",
                        "example": 1000000000,
                        "format": "int64",
                        "minimum": 0,
                        "type": "integer"
                    },
                    "offersIAP": {
                        "description": "OffersIAP is true when the listing offers in-app purchases (derived from\nthe presence of IAPRange).",
                        "example": true,
                        "type": "boolean"
                    },
                    "originalPrice": {
                        "description": "OriginalPrice is the pre-discount price in major currency units (micros\ndivided down); present only while a promotional discount is active.",
                        "example": 9.99,
                        "minimum": 0,
                        "type": "number"
                    },
                    "preregister": {
                        "description": "Preregister is true for an unreleased app open for pre-registration.",
                        "example": false,
                        "type": "boolean"
                    },
                    "previewVideo": {
                        "description": "PreviewVideo is the autoplay mp4 preview clip URL; absent when there is none.",
                        "format": "uri",
                        "type": "string"
                    },
                    "price": {
                        "description": "Price is the purchase price in major currency units (already divided down\nfrom Google's micros). 0 for free apps; see Currency for the unit.",
                        "example": 0,
                        "minimum": 0,
                        "type": "number"
                    },
                    "priceText": {
                        "description": "PriceText is the formatted price label (e.g. \"$4.99\"); empty for free apps.",
                        "example": "",
                        "type": "string"
                    },
                    "privacyPolicy": {
                        "description": "PrivacyPolicy is the developer's privacy-policy URL; may be absent.",
                        "example": "http://www.google.com/policies/privacy",
                        "format": "uri",
                        "type": "string"
                    },
                    "ratings": {
                        "description": "Ratings is the total number of star ratings.",
                        "example": 19445897,
                        "minimum": 0,
                        "type": "integer"
                    },
                    "recentChanges": {
                        "description": "RecentChanges is the latest \"What's new\" changelog text; may be absent.",
                        "type": "string"
                    },
                    "released": {
                        "description": "Released is the original release date as a Unix epoch in SECONDS, e.g.\n1352989068 (= 2012-11-15). 0 when absent. Symmetric with Updated.",
                        "example": 1352989068,
                        "format": "int64",
                        "minimum": 0,
                        "type": "integer"
                    },
                    "reviews": {
                        "description": "Reviews is the number of written text reviews (a subset of Ratings).",
                        "example": 677911,
                        "minimum": 0,
                        "type": "integer"
                    },
                    "score": {
                        "description": "Score is the average star rating, a float in [0,5] at full precision\n(ScoreText holds the rounded one-decimal label Google displays).",
                        "example": 4.626984,
                        "maximum": 5,
                        "minimum": 0,
                        "type": "number"
                    },
                    "scoreText": {
                        "description": "ScoreText is the rounded, one-decimal rating label as displayed, e.g.\n\"4.6\"; empty when the app has no rating.",
                        "example": "4.6",
                        "type": "string"
                    },
                    "screenshots": {
                        "description": "Screenshots is the list of screenshot image URLs.",
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "summary": {
                        "description": "Summary is the short tagline shown under the title. It may contain HTML\nentities exactly as Google serves them (e.g. \"\u0026amp;\").",
                        "example": "Real-time GPS navigation \u0026amp; local suggestions",
                        "type": "string"
                    },
                    "title": {
                        "description": "Title is the localized app name.",
                        "example": "Google Maps",
                        "type": "string"
                    },
                    "updated": {
                        "description": "Updated is the last-updated time as a Unix epoch in SECONDS. 0 when absent.",
                        "example": 1779963225,
                        "format": "int64",
                        "minimum": 0,
                        "type": "integer"
                    },
                    "url": {
                        "description": "URL is the canonical Play Store listing URL.",
                        "example": "https://play.google.com/store/apps/details?id=com.king.candycrushsaga",
                        "format": "uri",
                        "type": "string"
                    },
                    "version": {
                        "description": "Version is the current version string; may be empty when Google reports\n\"Varies with device\".",
                        "example": "1.329.0.1",
                        "type": "string"
                    },
                    "video": {
                        "description": "Video is the YouTube trailer player URL; absent on most non-game listings.",
                        "format": "uri",
                        "type": "string"
                    },
                    "videoImage": {
                        "description": "VideoImage is the trailer poster image URL; absent when there is no trailer.",
                        "format": "uri",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "apidoc.AvailabilityResult": {
                "properties": {
                    "appId": {
                        "description": "AppID is the probed app.",
                        "example": "com.google.android.apps.maps",
                        "type": "string"
                    },
                    "checked": {
                        "description": "Checked is the number of countries that produced a conclusive status\n(anything other than StatusFetchError).",
                        "example": 242,
                        "minimum": 0,
                        "type": "integer"
                    },
                    "errors": {
                        "additionalProperties": {
                            "type": "string"
                        },
                        "description": "Errors maps a country to the underlying error, populated only for\nStatusFetchError outcomes. It is nil when no probe errored. Serialized as a\ncountry-to-message map.",
                        "type": "object"
                    },
                    "globallyRemoved": {
                        "description": "GloballyRemoved is true only when at least one country was conclusively\nprobed and every conclusive (non-error) probe returned StatusNotFound —\ni.e. the app appears to have no listing anywhere it was checked. It is only\nmeaningful on a full AllCountries sweep; on a narrow Countries set it\nmerely reflects that subset. Note that AllCountries excludes markets\nwithout an official Play Store (cn/ir/kp/sy), so \"globally\" means across\nthe Play markets, not literally every country.",
                        "example": false,
                        "type": "boolean"
                    },
                    "statuses": {
                        "additionalProperties": {
                            "$ref": "#/components/schemas/googleplayscraper.Status"
                        },
                        "description": "Statuses maps each probed gl country code to its Status. Countries that\nwere never reached (e.g. due to context cancellation) are absent.",
                        "type": "object"
                    }
                },
                "type": "object"
            },
            "apidoc.DataSafety": {
                "properties": {
                    "collectedData": {
                        "description": "CollectedData lists data the app collects; may be empty.",
                        "items": {
                            "$ref": "#/components/schemas/googleplayscraper.DataSafetyEntry"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "privacyPolicyUrl": {
                        "description": "PrivacyPolicyURL is the privacy-policy URL from the data-safety page.",
                        "example": "http://www.google.com/policies/privacy",
                        "format": "uri",
                        "type": "string"
                    },
                    "securityPractices": {
                        "description": "SecurityPractices lists the developer's declared security practices.",
                        "items": {
                            "$ref": "#/components/schemas/googleplayscraper.SecurityPractice"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "sharedData": {
                        "description": "SharedData lists data the app shares with third parties; may be empty.",
                        "items": {
                            "$ref": "#/components/schemas/googleplayscraper.DataSafetyEntry"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "type": "object"
            },
            "apidoc.ErrorResponse": {
                "properties": {
                    "code": {
                        "description": "Code is the upstream HTTP status the scraper observed, copied verbatim into\nStatusError.Code. 404 = listing not found, 429 = rate-limited / anti-bot,\n5xx = upstream Google error.",
                        "example": 404,
                        "type": "integer"
                    },
                    "message": {
                        "description": "Message is the human-readable error string, matching StatusError.Error().",
                        "example": "unexpected status: 404",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "apidoc.Permission": {
                "properties": {
                    "permission": {
                        "description": "Permission is the human-readable permission description, e.g.\n\"precise location\".",
                        "example": "precise location",
                        "type": "string"
                    },
                    "type": {
                        "description": "Type is the permission group label, e.g. \"Location\", \"Camera\". Falls back\nto \"Common\"/\"Other\" when the group is unnamed.",
                        "example": "Location",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "apidoc.ReviewsResult": {
                "properties": {
                    "nextToken": {
                        "description": "NextToken is the continuation token for the next batchexecute page; empty\nwhen there are no more reviews.",
                        "example": "CroBIrEBAU60USc0jm2Ps4haLPoSm2pV",
                        "type": "string"
                    },
                    "reviews": {
                        "description": "Reviews is the page of parsed reviews.",
                        "items": {
                            "$ref": "#/components/schemas/googleplayscraper.Review"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "type": "object"
            },
            "apidoc.SearchResult": {
                "properties": {
                    "appId": {
                        "description": "AppID is the app package name.",
                        "example": "com.king.candycrushsaga",
                        "type": "string"
                    },
                    "currency": {
                        "description": "Currency is the ISO 4217 code for Price; often empty in compact results.",
                        "example": "",
                        "type": "string"
                    },
                    "developer": {
                        "description": "Developer is the developer's display name.",
                        "example": "King",
                        "type": "string"
                    },
                    "developerId": {
                        "description": "DeveloperID is the developer listing id.",
                        "example": "King",
                        "type": "string"
                    },
                    "free": {
                        "description": "Free is true when Price == 0.",
                        "example": true,
                        "type": "boolean"
                    },
                    "icon": {
                        "description": "Icon is the app icon URL.",
                        "example": "https://play-lh.googleusercontent.com/...=s64",
                        "format": "uri",
                        "type": "string"
                    },
                    "price": {
                        "description": "Price is the purchase price in major currency units; 0 for free apps.",
                        "example": 0,
                        "minimum": 0,
                        "type": "number"
                    },
                    "score": {
                        "description": "Score is the average star rating, a float in [0,5] at full precision.",
                        "example": 4.5100965,
                        "maximum": 5,
                        "minimum": 0,
                        "type": "number"
                    },
                    "scoreText": {
                        "description": "ScoreText is the rounded, one-decimal rating label, e.g. \"4.6\".",
                        "example": "4.5",
                        "type": "string"
                    },
                    "summary": {
                        "description": "Summary is the short tagline; may contain HTML entities as served.",
                        "type": "string"
                    },
                    "title": {
                        "description": "Title is the localized app name.",
                        "example": "Candy Crush Saga",
                        "type": "string"
                    },
                    "url": {
                        "description": "URL is the canonical Play Store listing URL.",
                        "example": "https://play.google.com/store/apps/details?id=com.king.candycrushsaga",
                        "format": "uri",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "googleplayscraper.Criteria": {
                "properties": {
                    "name": {
                        "description": "Name is the aspect being rated, e.g. \"Gameplay\" or \"Graphics\".",
                        "example": "Gameplay",
                        "type": "string"
                    },
                    "rating": {
                        "description": "Rating is the aspect's star rating, an integer 1..5.",
                        "example": 4,
                        "maximum": 5,
                        "minimum": 1,
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "googleplayscraper.DataSafetyEntry": {
                "properties": {
                    "data": {
                        "description": "Data is the specific data item name, e.g. \"Email address\".",
                        "example": "Email address",
                        "type": "string"
                    },
                    "optional": {
                        "description": "Optional is true when collection/sharing of this item is optional\n(false = required).",
                        "example": true,
                        "type": "boolean"
                    },
                    "purpose": {
                        "description": "Purpose is the comma-separated list of declared purposes, e.g.\n\"App functionality, Analytics\".",
                        "example": "App functionality, Account management",
                        "type": "string"
                    },
                    "type": {
                        "description": "Type is the category this item belongs to, e.g. \"Personal info\".",
                        "example": "Personal info",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "googleplayscraper.Review": {
                "properties": {
                    "criterias": {
                        "description": "Criterias holds per-aspect sub-ratings (e.g. gameplay, graphics); present\nmainly on games and absent on most apps.",
                        "items": {
                            "$ref": "#/components/schemas/googleplayscraper.Criteria"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "date": {
                        "description": "Date is when the review was posted, as a timezone-aware timestamp\n(serialized RFC 3339).",
                        "example": "2026-04-21T23:00:45.167+02:00",
                        "format": "date-time",
                        "type": "string"
                    },
                    "id": {
                        "description": "ID is the opaque review identifier (a UUID-like string).",
                        "example": "8f3c1d2e-1a2b-4c5d-9e0f-112233445566",
                        "type": "string"
                    },
                    "replyDate": {
                        "description": "ReplyDate is when the developer replied; zero/absent when there is no\nreply (serialized RFC 3339).",
                        "format": "date-time",
                        "type": "string"
                    },
                    "replyText": {
                        "description": "ReplyText is the developer's reply body; absent when there is no reply.",
                        "type": "string"
                    },
                    "score": {
                        "description": "Score is the star rating, an integer 1..5.",
                        "example": 5,
                        "maximum": 5,
                        "minimum": 1,
                        "type": "integer"
                    },
                    "text": {
                        "description": "Text is the review body.",
                        "example": "Works great, exactly what I needed.",
                        "type": "string"
                    },
                    "thumbsUp": {
                        "description": "ThumbsUp is the count of users who found the review helpful.",
                        "example": 16,
                        "minimum": 0,
                        "type": "integer"
                    },
                    "url": {
                        "description": "URL is the canonical link to the review on the Play Store.",
                        "example": "https://play.google.com/store/apps/details?id=com.example\u0026reviewId=8f3c1d2e",
                        "format": "uri",
                        "type": "string"
                    },
                    "userImage": {
                        "description": "UserImage is the URL of the author's avatar.",
                        "example": "https://play-lh.googleusercontent.com/a/AGNmyx...=s64",
                        "format": "uri",
                        "type": "string"
                    },
                    "userName": {
                        "description": "UserName is the review author's display name.",
                        "example": "Jane Doe",
                        "type": "string"
                    },
                    "version": {
                        "description": "Version is the app version the review was left on; may be absent.",
                        "example": "26.15.01.894202351",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "googleplayscraper.SecurityPractice": {
                "properties": {
                    "description": {
                        "description": "Description is the practice detail; it may contain inline HTML (e.g. an\nanchor tag) exactly as Google serves it.",
                        "example": "Your data is transferred over a secure connection",
                        "type": "string"
                    },
                    "practice": {
                        "description": "Practice is the practice headline, e.g. \"Data is encrypted in transit\".",
                        "example": "Data is encrypted in transit",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "googleplayscraper.Status": {
                "enum": [
                    0,
                    1,
                    2,
                    3,
                    4
                ],
                "type": "integer",
                "x-enum-varnames": [
                    "StatusUnknown",
                    "StatusAvailable",
                    "StatusNotInRegion",
                    "StatusNotFound",
                    "StatusFetchError"
                ]
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "license": {
            "name": "MIT",
            "url": "https://github.com/kryuchenko/google-play-scraper/blob/main/LICENSE"
        },
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "google-play-scraper source",
        "url": "https://github.com/kryuchenko/google-play-scraper"
    },
    "paths": {
        "/_/PlayStoreUi/data/batchexecute(IJ4APc)": {
            "post": {
                "description": "POST /_/PlayStoreUi/data/batchexecute?rpcids=IJ4APc. Returns the\nbatchexecute envelope; a []string of suggested query terms is\ndecoded from the inner payload.",
                "operationId": "batchSuggestIJ4APc",
                "parameters": [
                    {
                        "description": "Fixed rpcid for this operation",
                        "in": "query",
                        "name": "rpcids",
                        "required": true,
                        "schema": {
                            "enum": [
                                "IJ4APc"
                            ],
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "title": "f.req",
                                        "type": "string"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "URL-encoded JSON envelope [[['IJ4APc','\u003cinner-args\u003e']]]",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "items": {
                                        "type": "string"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "Suggested terms decoded from batchexecute envelope. An empty/null inner payload means no suggestions, not an error."
                    },
                    "429": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "batchexecute-envelope",
                    "x-rpcid": "IJ4APc"
                },
                "summary": "Search suggestions RPC (IJ4APc)",
                "tags": [
                    "batchexecute-rpc"
                ]
            }
        },
        "/_/PlayStoreUi/data/batchexecute(oCPfdb)": {
            "post": {
                "description": "POST /_/PlayStoreUi/data/batchexecute. Unlike the other RPCs the\nscraper does NOT put rpcids in the query string; the rpcid lives\nonly inside the f.req body. Handles both the initial fetch and\npagination. Returns the batchexecute envelope; ReviewsResult\n(reviews + nextToken) is decoded from the inner payload.",
                "operationId": "batchReviewsOCPfdb",
                "parameters": [
                    {
                        "description": "Review sort order (Sort enum, constants.go): 1=helpfulness, 2=newest, 3=rating. Default 2 (newest). NOTE: not a real query field — this value is embedded inside the f.req inner args; it is documented as a parameter only to surface the enum.",
                        "in": "query",
                        "name": "sort",
                        "schema": {
                            "enum": [
                                1,
                                2,
                                3
                            ],
                            "maximum": 3,
                            "minimum": 1,
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Reviews per request; embedded in f.req, capped at 150 by Google (reviews.go). Documented as a parameter only to surface the limit.",
                        "in": "query",
                        "name": "count",
                        "schema": {
                            "maximum": 150,
                            "minimum": 1,
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "title": "f.req",
                                        "type": "string"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "URL-encoded JSON envelope [[['oCPfdb','\u003cinner-args\u003e',null,'generic']]]. The sort order, page size and pagination token all live inside the inner args, NOT as query fields.",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ReviewsResult"
                                }
                            }
                        },
                        "description": "Decoded from batchexecute envelope. An empty/null inner payload means no more reviews (end of pagination), not an error; nextToken is then empty."
                    },
                    "429": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "batchexecute-envelope",
                    "x-rpcid": "oCPfdb"
                },
                "summary": "Reviews RPC (oCPfdb)",
                "tags": [
                    "batchexecute-rpc"
                ]
            }
        },
        "/_/PlayStoreUi/data/batchexecute(qnKhOb)": {
            "post": {
                "description": "POST /_/PlayStoreUi/data/batchexecute?rpcids=qnKhOb. Advances a\nlist, cluster or search result set using a continuation token.\nReturns the batchexecute envelope; []SearchResult plus the next\ntoken are decoded from the inner payload.",
                "operationId": "batchPaginateQnKhOb",
                "parameters": [
                    {
                        "description": "Fixed rpcid for this operation",
                        "in": "query",
                        "name": "rpcids",
                        "required": true,
                        "schema": {
                            "enum": [
                                "qnKhOb"
                            ],
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "title": "f.req",
                                        "type": "string"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "URL-encoded JSON carrying the continuation token",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/apidoc.SearchResult"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "Decoded from batchexecute envelope; includes next token. When pagination is exhausted Google returns 200 with a NULL inner payload (handled by decodeBatchEnvelope) — that signals end-of-data, not an error, and the next token is empty."
                    },
                    "429": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "batchexecute-envelope",
                    "x-rpcid": "qnKhOb"
                },
                "summary": "Paginate list/cluster/search RPC (qnKhOb)",
                "tags": [
                    "batchexecute-rpc"
                ]
            }
        },
        "/_/PlayStoreUi/data/batchexecute(vyAe2)": {
            "post": {
                "description": "POST /_/PlayStoreUi/data/batchexecute?rpcids=vyAe2. Body is the\nurl-encoded f.req from list_payload.txt with __NUM__,\n__COLLECTION__ and __CATEGORY__ substituted. Returns the\nbatchexecute envelope; []SearchResult is decoded from the inner\npayload. The #vyAe2 path fragment only disambiguates this\noperation and is not sent to the server.",
                "operationId": "batchListVyAe2",
                "parameters": [
                    {
                        "description": "Fixed rpcid for this operation",
                        "in": "query",
                        "name": "rpcids",
                        "required": true,
                        "schema": {
                            "enum": [
                                "vyAe2"
                            ],
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "title": "f.req",
                                        "type": "string"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "URL-encoded JSON envelope [[['vyAe2','\u003cinner-args\u003e',null,'generic']]]; inner __NUM__ is clamped to listMaxNum=660 (list.go)",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/apidoc.SearchResult"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "Decoded from batchexecute envelope. An empty/null inner payload means no data (end of the collection), not an error."
                    },
                    "429": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "batchexecute-envelope",
                    "x-rpcid": "vyAe2"
                },
                "summary": "List apps RPC (vyAe2)",
                "tags": [
                    "batchexecute-rpc"
                ]
            }
        },
        "/_/PlayStoreUi/data/batchexecute(xdSrCf)": {
            "post": {
                "description": "POST /_/PlayStoreUi/data/batchexecute?rpcids=xdSrCf. Returns the\nbatchexecute envelope; []Permission is decoded from the inner\npayload.",
                "operationId": "batchPermissionsXdSrCf",
                "parameters": [
                    {
                        "description": "Fixed rpcid for this operation",
                        "in": "query",
                        "name": "rpcids",
                        "required": true,
                        "schema": {
                            "enum": [
                                "xdSrCf"
                            ],
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "title": "f.req",
                                        "type": "string"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "URL-encoded JSON envelope [[['xdSrCf','\u003cinner-args\u003e',null,'1']]]",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/apidoc.Permission"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "Decoded from batchexecute envelope. An empty/null inner payload means the app declares no permissions, not an error."
                    },
                    "429": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "batchexecute-envelope",
                    "x-rpcid": "xdSrCf"
                },
                "summary": "Permissions RPC (xdSrCf)",
                "tags": [
                    "batchexecute-rpc"
                ]
            }
        },
        "/store/apps/category/{category}": {
            "get": {
                "description": "Returns text/html for a single category; parsed like the top\ncharts page into []SearchResult plus cluster URLs.",
                "operationId": "categoryApps",
                "parameters": [
                    {
                        "description": "Play category id, e.g. GAME, GAME_ACTION or PRODUCTIVITY. One of the 54 ids in AllCategories (constants.go); not enumerated here to avoid drift as Google adds/removes categories.",
                        "in": "path",
                        "name": "category",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "UI language, ISO 639-1, e.g. en",
                        "in": "query",
                        "name": "hl",
                        "schema": {
                            "maxLength": 5,
                            "minLength": 2,
                            "type": "string"
                        }
                    },
                    {
                        "description": "Country, ISO 3166-1 alpha-2 lowercase (pattern ^[a-z]{2}$, descriptive only), e.g. us",
                        "in": "query",
                        "name": "gl",
                        "schema": {
                            "maxLength": 2,
                            "minLength": 2,
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/apidoc.SearchResult"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "Category apps parsed from AF_initDataCallback"
                    },
                    "404": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "No such category page — the {category} id is not a recognized Play category. Surfaced as StatusError{Code:404}."
                    },
                    "429": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "AF_initDataCallback",
                    "x-rpcid": "none"
                },
                "summary": "Category page (HTML)",
                "tags": [
                    "html-endpoints"
                ]
            }
        },
        "/store/apps/collection/{clusterPath}": {
            "get": {
                "description": "GET of an absolute collection/cluster URL discovered on a list\nor similar-apps page. Returns text/html parsed into\n[]SearchResult. The path is dynamic, hence the {clusterPath}\nplaceholder.",
                "operationId": "getCluster",
                "parameters": [
                    {
                        "description": "Absolute cluster/collection path from a prior page",
                        "in": "path",
                        "name": "clusterPath",
                        "required": true,
                        "schema": {
                            "minLength": 1,
                            "type": "string"
                        }
                    },
                    {
                        "description": "UI language, ISO 639-1, e.g. en",
                        "in": "query",
                        "name": "hl",
                        "schema": {
                            "maxLength": 5,
                            "minLength": 2,
                            "type": "string"
                        }
                    },
                    {
                        "description": "Country, ISO 3166-1 alpha-2 lowercase (pattern ^[a-z]{2}$, descriptive only), e.g. us",
                        "in": "query",
                        "name": "gl",
                        "schema": {
                            "maxLength": 2,
                            "minLength": 2,
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/apidoc.SearchResult"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "Cluster apps parsed from AF_initDataCallback"
                    },
                    "404": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Cluster/collection URL no longer valid — tokens expire and clusters rotate. Surfaced as StatusError{Code:404}."
                    },
                    "429": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "AF_initDataCallback",
                    "x-rpcid": "none"
                },
                "summary": "Cluster page (HTML, absolute URL)",
                "tags": [
                    "html-endpoints"
                ]
            }
        },
        "/store/apps/datasafety": {
            "get": {
                "description": "Returns text/html. The DataSafety model is parsed from the\nAF_initDataCallback ` + "`" + `ds:3` + "`" + ` block.",
                "operationId": "getDataSafety",
                "parameters": [
                    {
                        "description": "App package id, reverse-domain form (pattern ^[a-zA-Z][a-zA-Z0-9_]*(\\.[a-zA-Z][a-zA-Z0-9_]*)+$, descriptive only), e.g. com.whatsapp",
                        "in": "query",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "maxLength": 255,
                            "minLength": 3,
                            "type": "string"
                        }
                    },
                    {
                        "description": "UI language, ISO 639-1, e.g. en",
                        "in": "query",
                        "name": "hl",
                        "schema": {
                            "maxLength": 5,
                            "minLength": 2,
                            "type": "string"
                        }
                    },
                    {
                        "description": "Country, ISO 3166-1 alpha-2 lowercase (pattern ^[a-z]{2}$, descriptive only), e.g. us",
                        "in": "query",
                        "name": "gl",
                        "schema": {
                            "maxLength": 2,
                            "minLength": 2,
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.DataSafety"
                                }
                            }
                        },
                        "description": "Data safety parsed from AF_initDataCallback ds:3. Unlike /store/apps/details, this page does NOT 404 for a removed or unknown app: it returns 200 with an empty ds:3 block and DataSafety() yields a zero-value result (nil error)."
                    },
                    "400": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Missing the required id query parameter — Google returns 400 for this endpoint (not 404)."
                    },
                    "429": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-data-block": "ds:3",
                    "x-response-encoding": "AF_initDataCallback",
                    "x-rpcid": "none"
                },
                "summary": "Data safety (HTML, ds:3)",
                "tags": [
                    "html-endpoints"
                ]
            }
        },
        "/store/apps/details": {
            "get": {
                "description": "Returns text/html. The App model is parsed from the\nAF_initDataCallback ` + "`" + `ds:5` + "`" + ` block, payload node [1][2].",
                "operationId": "getAppDetails",
                "parameters": [
                    {
                        "description": "App package id, reverse-domain form, pattern ^[a-zA-Z][a-zA-Z0-9_]*(\\.[a-zA-Z][a-zA-Z0-9_]*)+$ (pattern is descriptive only; swag v2 does not emit @Param pattern), e.g. com.whatsapp",
                        "in": "query",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "maxLength": 255,
                            "minLength": 3,
                            "type": "string"
                        }
                    },
                    {
                        "description": "UI language, ISO 639-1, usually 2 lowercase letters but locale variants like pt-BR occur, e.g. en",
                        "in": "query",
                        "name": "hl",
                        "schema": {
                            "maxLength": 5,
                            "minLength": 2,
                            "type": "string"
                        }
                    },
                    {
                        "description": "Country, ISO 3166-1 alpha-2 lowercase, pattern ^[a-z]{2}$ (descriptive only), e.g. us",
                        "in": "query",
                        "name": "gl",
                        "schema": {
                            "maxLength": 2,
                            "minLength": 2,
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.App"
                                }
                            }
                        },
                        "description": "App parsed from AF_initDataCallback ds:5[1][2]"
                    },
                    "404": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "App/listing not found — removed, never existed, or not distributed in this country (gl). Surfaced as StatusError{Code:404}."
                    },
                    "429": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-data-block": "ds:5",
                    "x-payload-node": "[1][2]",
                    "x-response-encoding": "AF_initDataCallback",
                    "x-rpcid": "none"
                },
                "summary": "App details (HTML, ds:5)",
                "tags": [
                    "html-endpoints"
                ]
            }
        },
        "/store/apps/details(availability)": {
            "get": {
                "description": "Reuses GET /store/apps/details per gl country. Availability is\nderived from node [18] of ` + "`" + `ds:5` + "`" + `[1][2]: [18][0]==2 available,\n==1 pre-registration, empty/missing not-in-region, HTTP 404\nnot-found. The aggregated sweep yields AvailabilityResult.",
                "operationId": "getAppAvailability",
                "parameters": [
                    {
                        "description": "App package id, reverse-domain form (pattern ^[a-zA-Z][a-zA-Z0-9_]*(\\.[a-zA-Z][a-zA-Z0-9_]*)+$, descriptive only), e.g. com.whatsapp",
                        "in": "query",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "maxLength": 255,
                            "minLength": 3,
                            "type": "string"
                        }
                    },
                    {
                        "description": "UI language, ISO 639-1, e.g. en",
                        "in": "query",
                        "name": "hl",
                        "schema": {
                            "maxLength": 5,
                            "minLength": 2,
                            "type": "string"
                        }
                    },
                    {
                        "description": "Country to probe, ISO 3166-1 alpha-2 lowercase (pattern ^[a-z]{2}$, descriptive only); one request per country, e.g. us",
                        "in": "query",
                        "name": "gl",
                        "required": true,
                        "schema": {
                            "maxLength": 2,
                            "minLength": 2,
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.AvailabilityResult"
                                }
                            }
                        },
                        "description": "Aggregated availability sweep; per-country Status read from ds:5[1][2][18]"
                    },
                    "404": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Probed country has no listing; at the per-country probe a 404 maps to Status not_found (StatusError{Code:404}) rather than failing the whole sweep."
                    },
                    "429": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sweeping many countries from one IP makes this likely; the failing country maps to Status error."
                    },
                    "500": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx); the failing country maps to Status error."
                    },
                    "x-data-block": "ds:5",
                    "x-payload-node": "[1][2][18]",
                    "x-response-encoding": "AF_initDataCallback",
                    "x-rpcid": "none"
                },
                "summary": "App availability probe (HTML, ds:5 node [18])",
                "tags": [
                    "html-endpoints"
                ]
            }
        },
        "/store/apps/dev": {
            "get": {
                "description": "Returns text/html. Used when the developer id is the numeric\ninternal id; results parsed into []SearchResult.",
                "operationId": "developerAppsNumeric",
                "parameters": [
                    {
                        "description": "Numeric developer id, digits only (pattern ^[0-9]+$, descriptive only), e.g. 5700313618786177705",
                        "in": "query",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "maxLength": 32,
                            "minLength": 1,
                            "type": "string"
                        }
                    },
                    {
                        "description": "UI language, ISO 639-1, e.g. en",
                        "in": "query",
                        "name": "hl",
                        "schema": {
                            "maxLength": 5,
                            "minLength": 2,
                            "type": "string"
                        }
                    },
                    {
                        "description": "Country, ISO 3166-1 alpha-2 lowercase (pattern ^[a-z]{2}$, descriptive only), e.g. us",
                        "in": "query",
                        "name": "gl",
                        "schema": {
                            "maxLength": 2,
                            "minLength": 2,
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/apidoc.SearchResult"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "Developer apps parsed from AF_initDataCallback"
                    },
                    "404": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "No such developer page — the numeric id does not exist or is not distributed in this country (gl). Surfaced as StatusError{Code:404}."
                    },
                    "429": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "AF_initDataCallback",
                    "x-rpcid": "none"
                },
                "summary": "Developer apps by numeric id (HTML)",
                "tags": [
                    "html-endpoints"
                ]
            }
        },
        "/store/apps/developer": {
            "get": {
                "description": "Returns text/html. Used when the developer id is a human-readable\nname; results parsed into []SearchResult.",
                "operationId": "developerAppsName",
                "parameters": [
                    {
                        "description": "Human-readable developer name, e.g. Google LLC",
                        "in": "query",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "maxLength": 255,
                            "minLength": 1,
                            "type": "string"
                        }
                    },
                    {
                        "description": "UI language, ISO 639-1, e.g. en",
                        "in": "query",
                        "name": "hl",
                        "schema": {
                            "maxLength": 5,
                            "minLength": 2,
                            "type": "string"
                        }
                    },
                    {
                        "description": "Country, ISO 3166-1 alpha-2 lowercase (pattern ^[a-z]{2}$, descriptive only), e.g. us",
                        "in": "query",
                        "name": "gl",
                        "schema": {
                            "maxLength": 2,
                            "minLength": 2,
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/apidoc.SearchResult"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "Developer apps parsed from AF_initDataCallback"
                    },
                    "404": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "No such developer page — the name does not match a developer or is not distributed in this country (gl). Surfaced as StatusError{Code:404}."
                    },
                    "429": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "AF_initDataCallback",
                    "x-rpcid": "none"
                },
                "summary": "Developer apps by name (HTML)",
                "tags": [
                    "html-endpoints"
                ]
            }
        },
        "/store/apps/top": {
            "get": {
                "description": "Returns text/html. Used both to parse the initial []SearchResult\nand to discover collection/cluster URLs for paging.",
                "operationId": "topApps",
                "parameters": [
                    {
                        "description": "UI language, ISO 639-1, e.g. en",
                        "in": "query",
                        "name": "hl",
                        "schema": {
                            "maxLength": 5,
                            "minLength": 2,
                            "type": "string"
                        }
                    },
                    {
                        "description": "Country, ISO 3166-1 alpha-2 lowercase (pattern ^[a-z]{2}$, descriptive only), e.g. us",
                        "in": "query",
                        "name": "gl",
                        "schema": {
                            "maxLength": 2,
                            "minLength": 2,
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/apidoc.SearchResult"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "Top apps parsed from AF_initDataCallback"
                    },
                    "429": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "AF_initDataCallback",
                    "x-rpcid": "none"
                },
                "summary": "Top charts page (HTML)",
                "tags": [
                    "html-endpoints"
                ]
            }
        },
        "/store/search": {
            "get": {
                "description": "Returns text/html; []SearchResult and an optional pagination\ntoken are parsed from the embedded AF_initDataCallback blocks.",
                "operationId": "searchApps",
                "parameters": [
                    {
                        "description": "Search query term",
                        "in": "query",
                        "name": "q",
                        "required": true,
                        "schema": {
                            "maxLength": 255,
                            "minLength": 1,
                            "type": "string"
                        }
                    },
                    {
                        "description": "Corpus; the scraper always sends 'apps'",
                        "in": "query",
                        "name": "c",
                        "required": true,
                        "schema": {
                            "enum": [
                                "apps"
                            ],
                            "type": "string"
                        }
                    },
                    {
                        "description": "Price filter: 0=all, 1=free, 2=paid (see search.go getPriceValue)",
                        "in": "query",
                        "name": "price",
                        "schema": {
                            "enum": [
                                0,
                                1,
                                2
                            ],
                            "maximum": 2,
                            "minimum": 0,
                            "type": "integer"
                        }
                    },
                    {
                        "description": "UI language, ISO 639-1, e.g. en",
                        "in": "query",
                        "name": "hl",
                        "schema": {
                            "maxLength": 5,
                            "minLength": 2,
                            "type": "string"
                        }
                    },
                    {
                        "description": "Country, ISO 3166-1 alpha-2 lowercase (pattern ^[a-z]{2}$, descriptive only), e.g. us",
                        "in": "query",
                        "name": "gl",
                        "schema": {
                            "maxLength": 2,
                            "minLength": 2,
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/apidoc.SearchResult"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "Search results parsed from AF_initDataCallback. No match is NOT a 404: Google returns 200 with an empty result set, decoded as an empty array."
                    },
                    "429": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Rate-limited / anti-bot challenge. Google may return 429, or 200 redirecting to google.com/sorry (CAPTCHA). Sustained scraping from one IP triggers this."
                    },
                    "500": {
                        "content": {
                            "text/html": {
                                "schema": {
                                    "$ref": "#/components/schemas/apidoc.ErrorResponse"
                                }
                            }
                        },
                        "description": "Upstream Google error (any 5xx). Surfaced as StatusError with the observed code."
                    },
                    "x-response-encoding": "AF_initDataCallback",
                    "x-rpcid": "none"
                },
                "summary": "Search apps (HTML)",
                "tags": [
                    "html-endpoints"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "play.google.com/"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Title:            "Google Play Store private HTTP API (reverse-engineered)",
	Description:      "Reverse-engineered description of the PRIVATE, undocumented\nHTTP endpoints of the Google Play Store web frontend that the\ngoogle-play-scraper Go library calls.\n\nDISCLAIMER: These endpoints are NOT a public, supported Google\nAPI. This project is NOT affiliated with, endorsed by, or\nsponsored by Google. The endpoints are undocumented, may change\nor disappear without notice, and accessing them may be subject\nto the Google Play / Google Terms of Service. This spec is\nprovided for interoperability and educational purposes only.\n\nTwo response shapes appear:\n* AF_initDataCallback: GET endpoints return text/html whose\nbody embeds `AF_initDataCallback({key:'ds:N', data:[...]})`\nscript blocks; the scraper extracts the logical model from\na numbered data block (e.g. ds:5).\n* batchexecute envelope: POST /_/PlayStoreUi/data/batchexecute\nreturns a `)]}'`-prefixed, `wrb.fr`-framed envelope; the\nscraper decodes the inner URL-encoded JSON for the RPC.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
